grafana:
  
  grafana.ini:
    server:
      root_url: https://grafana.joshiharshal.cloud
    auth:
      disable_login_form: false
    auth.generic_oauth:
      enabled: true
      name: Keycloak
      allow_sign_up: true
      client_id: grafana
      client_secret: uMSgbiCZiQuyJGGt41oE40FWHGB2gZQz
      scopes: openid profile email
      auth_url: https://keycloak.joshiharshal.cloud/realms/grafana/protocol/openid-connect/auth
      token_url: https://keycloak.joshiharshal.cloud/realms/grafana/protocol/openid-connect/token
      api_url: https://keycloak.joshiharshal.cloud/realms/grafana/protocol/openid-connect/userinfo
      role_attribute_path: "contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'"

  

