loki:
  enabled: true
  isDefault: true
  persistence:
    enabled: true
    size: 5Gi

promtail:
  enabled: true
  serviceMonitor:
    enabled: true
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
    snippets:
      pipeline_stages:
        - docker: {}
        - cri: {}
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"

grafana:
  enabled: false  # You already have Grafana separately at grafana.joshiharshal.cloud                                                                                                                                                                                                                                         