config:
  clients:
    - url: https://loki.joshiharshal.cloud/loki/api/v1/push
      tls_config:
        insecure_skip_verify: true
  snippets:
    pipeline_stages:
      - docker: {}
      - cri: {}
    extraScrapeConfigs: |
      - job_name: kubernetes-pods-custom
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              __path__: /var/log/containers/*.log

tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"

extraVolumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: containers
    hostPath:
      path: /var/lib/docker/containers

extraVolumeMounts:
  - name: varlog
    mountPath: /var/log
    readOnly: true
  - name: containers
    mountPath: /var/lib/docker/containers
    readOnly: true
                                                                                                                                                                                                                                           
