{
 "title": "http-server-pod",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"172.31.26.253:9100\"} - node_memory_MemAvailable_bytes{instance=\"172.31.26.253:9100\"}) / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "pod",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\", pod=~\"simplehttp.*\"})\n",
     "legendFormat": "Total Pod"
    },
    { "expr": "count(kube_node_info)\n", "legendFormat": "Total Nodes" },
    {
     "expr": "count(kube_deployment_created) + count(kube_statefulset_created) + count(kube_daemonset_created)\n",
     "legendFormat": "Workload"
    }
   ]
  },
  {
   "title": "network_transmit_bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"simplehttp.*\", namespace=\"simple-http\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "logs",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{pod=\"simplehttp-deployment-7b854bb7c6-dkbvw\"} |= ``"
    }
   ]
  }
 ]
}