apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: keycloak
spec:
  secretName: keycloak-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - TachyonByte
  commonName: keycloak.joshiharshal.cloud
  dnsNames:
    - keycloak.joshiharshal.cloud
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
